name: BUILD-TEST
on: [push]
jobs:
  Init-Job:
    runs-on: windows-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This step is running."
  
  Build-Job:
    runs-on: [ self-hosted, BUILD-Runner]
    needs: [Init-Job]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Batch File
        shell: cmd
        run: DevScripts\build.bat
  Test-Job:
    runs-on: [ self-hosted, TEST-Runner]
    needs: [Build-Job]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Batch File
        shell: cmd
        run: DevScripts\test.bat
  
  Finalize-Job:
    runs-on: windows-latest
    needs: [Init-Job]
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "All previous jobs completed successfully."
