name: TEST only
on: [push]
jobs:
  Init-Job:
    runs-on: windows-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Read YAML configuration file
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: read_config
        with:
          config: DevScripts\configuration.yaml 
  
  Test-Job:
    runs-on: [ self-hosted, TEST-Runner]
    strategy:
      fail-fast: false  # Critical: Prevents auto-cancellation of jobs
      matrix:
        suite: [suite1, suite2, suite3]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run ${{ matrix.suite }}
        run: |
          echo "Running test suite: ${{ matrix.suite }}"
      - name: Run Test Batch File
        shell: cmd
        run: DevScripts\test.bat
        
  Finalize-Job:
    runs-on: windows-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "All previous jobs completed successfully."
