name: TEST only
on: [push]
jobs:
  Init-Job:
    runs-on: windows-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Read YAML configuration file
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: read_config
        with:
          config: DevScripts\configuration.yaml 
  Read-Test-Matrix:
    runs-on: ubuntu-latest
    outputs:
      suites: ${{ steps.set-matrix.outputs.suites }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          suites=$(jq -c '.suite' DevScripts/criteria_tests.json)
          echo "suites=$suites"
          echo "suites=$suites" >> $GITHUB_OUTPUT
  Test-Job:
    runs-on: [ self-hosted, TEST-Runner]
    needs: Read-Test-Matrix
    strategy:
      fail-fast: false  # Critical: Prevents auto-cancellation of jobs
      matrix:
        suite: ${{ fromJson(needs.Read-Test-Matrix.outputs.suites) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run ${{ matrix.suite }}
        run: |
          echo "Running test suite: ${{ matrix.suite }}"
      - name: Run Test Batch File
        shell: cmd
        run: DevScripts\test.bat
        
  Finalize-Job:
    runs-on: windows-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "All previous jobs completed successfully."
